### ISSUE TITLE
Bug Report | 

### ISSUE THREAD

**Issue by Overkeep** [Clientastisch/Cardinal-Anticheat#149]
What type of bug you want to report? Describe it here

crash
When does the bug occurr?

starting server
Cardinal Version:
 latest
Spigot Version:

 mspigot

> **Attached Files  (Required)**

[05:42:33] [Server thread/INFO]: [Cardinal] Enabling Cardinal v1.0.0
[05:42:38] [Server thread/INFO]: [0;31;1m[21m

                           .o88b.  .d8b.   .o88b.
                          d8P  Y8 d8' `8b d8P  Y8
                          8P      88ooo88 8P     
                          8b      88   88 8b     
                          Y8b  d8 88   88 Y8b  d8
                           `Y88P' YP   YP  `Y88P'
                                  
                                  
 
 
 _              _____ _ _            _            _   _          _     
| |            / ____| (_)          | |          | | (_)        | |    
| |__  _   _  | |    | |_  ___ _ __ | |_ __ _ ___| |_ _ ___  ___| |__  
| '_ \| | | | | |    | | |/ _ \ '_ \| __/ _` / __| __| / __|/ __| '_ \ 
| |_) | |_| | | |____| | |  __/ | | | || (_| \__ \ |_| \__ \ (__| | | |
|_.__/ \__, |  \_____|_|_|\___|_| |_|\__\__,_|___/\__|_|___/\___|_| |_|
        __/ |                                                          
       |___/                                                           
 
 
[m
[05:42:38] [Server thread/INFO]: Loaded Checks: [0;32;1m112[m
[05:42:38] [Server thread/INFO]: Using CPU: [0;32;22m2 [0;37;22m/[0;32;1m 2[m
[05:42:38] [Server thread/INFO]: Networks: [0;32;1mLoaded[m
[05:42:38] [pool-11-thread-4/INFO]: [Cardinal] Disabling Cardinal v1.0.0
[05:42:38] [pool-11-thread-4/INFO]: [0;31;1m[21mCAC[0;37;22m: Disabling [0;31;1mCAC[0;37;22m...[m
[05:42:38] [pool-11-thread-4/INFO]: [0;31;1m[21mCAC[0;37;22m: This could take a while[m
[05:42:38] [Server thread/INFO]: Resource: [0;32;1mLoaded[m
[05:42:38] [Server thread/INFO]: Replay: [0;31;1mDisabled[m
[05:42:38] [pool-11-thread-4/ERROR]: Error occurred while disabling Cardinal v1.0.0 (Is it up to date?)
java.lang.NullPointerException
	at me.clientastisch.core.Core.onPreTerminate(Unknown Source) ~[?:?]
	at me.clientastisch.core.Plugin.onDisable(Unknown Source) ~[?:?]
	at me.clientastisch.cardinal.core.Core.onDisable(Core.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318) ~[server.jar:git-mSpigot-unknown]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356) ~[server.jar:git-mSpigot-unknown]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:436) ~[server.jar:git-mSpigot-unknown]
	at me.clientastisch.core.Plugin.deactivate(Unknown Source) ~[?:?]
	at me.clientastisch.core.Core.lambda$null$0(Unknown Source) ~[?:?]
	at me.clientastisch.netty.network.Handshake.<init>(Unknown Source) ~[?:?]
	at me.clientastisch.core.Core.lambda$init$1(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[05:42:38] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Required plugin Cardinal v1.0.0 failed to load (server will shutdown)
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.pluginFailedToLoad(CraftServer.java:374) ~[server.jar:git-mSpigot-unknown]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:510) ~[server.jar:git-mSpigot-unknown]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:411) ~[server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.MinecraftServer.n(MinecraftServer.java:380) ~[server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.MinecraftServer.g(MinecraftServer.java:354) ~[server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.MinecraftServer.a(MinecraftServer.java:310) ~[server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:205) ~[server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:481) [server.jar:git-mSpigot-unknown]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [server.jar:git-mSpigot-unknown]
[05:42:38] [Server thread/ERROR]: This crash report has been saved to: /home/Practice/./crash-reports/crash-2021-01-08_05.42.38-server.txt
[05:42:38] [Server thread/INFO]: Stopping server

cant upload spigot its too big msg me on discord Sp4lding#7358

**Comment by SingleUserxd** [comment]
This plugin doesn't support mSpigot.

**Comment by Clientastisch** [comment]
<img src="https://i.imgur.com/TAykl4g.png" />

As you can see, it doesn't support 1.7 at all
