### ISSUE TITLE
Bug Report | Cardinal not starting

### ISSUE THREAD

**Issue by AdamCraftmaster** [Clientastisch/Cardinal-Anticheat#151]
What type of bug you want to report? Describe it here
Whenever starting a server, cardinal attempts to start for around 2 minutes, then crashes. 

When does the bug occurr?
Whenever starting the server.

Cardinal Version:
1.0002

Spigot Version:
CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

> **Attached Files  (Required)**

[15:39:54] [Server thread/INFO]: [Cardinal] Enabling Cardinal v1.0.0
[15:42:04] [Server thread/ERROR]: Error occurred while enabling Cardinal v1.0.0 (Is it up to date?)
java.lang.ClassNotFoundException: me.clientastisch.core.Core
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at me.clientastisch.cardinal.core.Core.onEnable(Core.java:27) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [server.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [server.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [server.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by Clientastisch** [comment]
Do you run your server on some special environment?

**Comment by AdamCraftmaster** [comment]
> Do you run your server on some special environment?

yes, I am running in pterodactyl. (docker container with java 1.8, but I tried Java 11 as well)

**Comment by Clientastisch** [comment]
Minecraft won't run on Java 11 anyway...
Make sure you don't prevent your server from communicting with other servers outside your environment.
As for how to configurate the containers in order to make this plugin work, I can't help you.
This is my second time hearing this, however it does work on plain docker. I can just assume, that the issue is some configuration (probably by default) ...

**Comment by AdamCraftmaster** [comment]
That might be the issue that the container is isolated from networks other than the port given to it, I will try and fix that on my end. Also, Paperspigot needs java 11 now, and so do some more advanced plugins.
