### ISSUE TITLE
Bug Report | CacApi

### ISSUE THREAD

**Issue by coolpvpv1** [Clientastisch/Cardinal-Anticheat#9]
What type of bug you want to report? Describe it here
cacapi wont load in the plugins folder its done that ever sense first release so i guess i should just report it

When the bug occurrs?
i just put them in the plugins folder and loaded up the server and it gives me this
[16:07:15 ERROR]: Could not load 'plugins\CACApi.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:154) ~[spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 6 more

Cardinal Version: 0.9956 (newest version)
Spigot Version: 1.8.8

Attached Files
from the download link in spigotmc i guess?

**Comment by Clientastisch** [comment]
Ough yeah, my mistake.
I should have explaine the API a bit more.

Creating an addon requires the following:

- Add CACAPI.jar and Spigot.jar to your project
- Create a file named addon.jason instead of plugin.yml like this:
```
{
  "name": "TestPlugin",
  "author": "YourName",
  "main": "my.path.to.Main",
  "version": "1.0"
}
```
- Export your project to /plugins/CAC/addons
